language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

go:
  - 1.13.x


# Only clone the most recent commit.
git:
  depth: 1

matrix:
  include:
    - name: "Lint"
      script:
        - rm -rf $HOME/.cache/golangci-lint || true
        - make lint

    - name: "Unit Tests"
      before_script:
        - go get ./...

      # Send a notification to the Dusk build Status Telegram channel once the CI build completes
      after_script:
        - bash <(curl -s https://raw.githubusercontent.com/dusk-network/tools/master/bash/telegram_ci_notifications.sh)

      script:
        - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... # Run all the tests with the race detector enabled

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - name: "Test Harness"
      script:
        - make test-harness-ci
